import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, Check, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, X } from 'lucide-react'
import './styles.css'

const company = { name:'M FURNITURE PTE. LTD.', email:'MFURNITURESHOP@outlook.com', address:['60 PAYA LEBAR ROAD','#11-53','PAYA LEBAR SQUARE','SINGAPORE (409051)'] }
const categories = [
  { id:'kitchen', label:'Kitchen rituals', note:'Order that feels good', items:[['Brushed steel saucepan',49],['Carbon non-stick skillet',42],['Fresh-lock container trio',28],['Pantry seal canister',19],['Rolling rice keeper',64],['Four-spice station',32],['Counter tier rack',45],['Soft-close storage box',34],['Dish drain station',39],['Silicone saver pouch',16]] },
  { id:'living', label:'Living & bedroom', note:'Make room to unwind', items:[['Tailored platform bed',299],['Cove side table',89],['Moss lounge chair',189],['Nine-cube shelf',119],['Low-profile storage bench',149],['Quiet texture rug',139],['Boucle cloud cushion',32],['Dusk curtain panel',49],['Walnut bedside lamp',69],['Foldaway lounge chair',109]] },
  { id:'utility', label:'Bath & utility', note:'Small systems, calmer days', items:[['Foldaway drying rack',56],['Tall weave laundry basket',48],['Over-door towel rail',29],['Fold-flat laundry hamper',39],['Rolling utility cart',74],['Entryway hook rail',24],['Woven-look shower curtain',35],['Soft pedal bin',46],['Retractable clothesline',31],['Compact step stool',22]] },
  { id:'work', label:'Work from home', note:'A better place to focus', items:[['Posture mesh chair',239],['Air-knit task chair',199],['Contour gaming chair',259],['Linework writing desk',179],['Lift laptop stand',42],['Desk drawer organizer',29],['Arc task lamp',54],['Felt desk mat',32],['Cable calm box',26],['Rolling underdesk drawer',79]] },
  { id:'comfort', label:'Comfort & storage', note:'Softness with a purpose', items:[['Cloud fleece throw',38],['Olive lumbar cushion',29],['Round floor cushion',44],['Canvas storage trunk',79],['Stackable shoe box',22],['Underbed fabric case',34],['Tall weave hamper',58],['Carry night light',49],['Folding perch stool',36],['Three-tier shelf',89]] },
]
const products = categories.flatMap((cat) => cat.items.map(([name, price], i) => ({ id:`${cat.id}-${i}`, category:cat.id, name, price, image:`/products/product-${String(categories.indexOf(cat)*10+i+1).padStart(2,'0')}.webp`, tag:i === 0 ? 'New rhythm' : i === 3 ? 'Bestseller' : '' })))
const pages = { about:['About us','YENFER curates useful, good-looking essentials for the everyday home. We believe comfort is built from small, intentional choices — a clear counter, a softer landing, a better light.'], shipping:['Shipping policy','Orders are prepared within 1–3 business days. Delivery windows and tracking updates are shared by email after dispatch. Shipping rates are shown at checkout before payment.'], tracking:['Order tracking','Enter the tracking reference from your dispatch email. For help locating an order, contact MFURNITURESHOP@outlook.com with your order number.'], terms:['Terms of Service','These Terms of Service establish the rules for using YENFER and purchasing from M FURNITURE PTE. LTD.'], privacy:['Privacy policy','We use the information you provide to process orders, provide support, and send service updates. We do not sell personal information.'], dmca:['DMCA','If you believe content on this site infringes your rights, send a clear notice to MFURNITURESHOP@outlook.com identifying the work and the material in question.'], payments:['Payment & security','Checkout is a frontend demonstration. Payment options shown are PayPal, Visa, and credit/debit card. No live charge is processed in this demo.'], returns:['Returns & refunds','Request a return within 14 days of delivery for unused, resalable goods. Approved refunds are returned to the original payment method.'], cancellation:['Cancellation policy','You may request cancellation before dispatch by emailing the company with your order number. Once dispatched, the returns policy applies.'] }
const terms = ['Acceptance of terms','Eligibility and account information','Product descriptions','Prices and availability','Orders and acceptance','Payment authorization','Shipping and delivery','Returns and refunds','Cancellations','Intellectual property','User content','Prohibited uses','Third-party services','Disclaimer of warranties','Limitation of liability','Indemnification','Governing law and contact']

function App(){
  const [cart,setCart]=useState([]), [cartOpen,setCartOpen]=useState(false), [view,setView]=useState(location.hash==='#/admin'?'admin':'home'), [filter,setFilter]=useState('all'), [query,setQuery]=useState(''), [mobile,setMobile]=useState(false)
  const add=(p,buy=false)=>{ setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]); setCartOpen(true); if(buy) setView('checkout') }
  const update=(id,delta)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+delta}:x).filter(x=>x.qty>0))
  const total=cart.reduce((s,x)=>s+x.price*x.qty,0), count=cart.reduce((s,x)=>s+x.qty,0)
  const shown=useMemo(()=>products.filter(p=>(filter==='all'||p.category===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[filter,query])
  const go=(v)=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})}
  if(view==='admin') return <Admin go={go}/>
  if(view==='checkout') return <Checkout cart={cart} total={total} go={go}/>
  if(view!=='home') return <InfoPage page={pages[view]} terms={view==='terms'} go={go}/>
  return <><header className="topbar"><a className="wordmark" onClick={()=>go('home')}>YENFER<span>®</span></a><nav className={mobile?'open':''}><a onClick={()=>go('home')}>Shop</a><a onClick={()=>go('about')}>Our point of view</a><a onClick={()=>go('shipping')}>Shipping</a></nav><div className="actions"><button className="icon-btn" onClick={()=>document.querySelector('.catalog')?.scrollIntoView({behavior:'smooth'})}><Search size={18}/></button><button className="bag-btn" onClick={()=>setCartOpen(true)}>Bag <b>{count}</b></button><button className="icon-btn menu-btn" onClick={()=>setMobile(!mobile)}><Menu size={19}/></button></div></header>
    <main><section className="hero"><div className="hero-copy"><p className="eyebrow">HOME, EDITED DAILY</p><h1>Everyday,<br/><em>considered.</em></h1><p className="hero-lede">Useful objects with a little more thought in them. YENFER brings calm, character and function to the places you live in.</p><button className="dark-btn" onClick={()=>document.querySelector('.catalog')?.scrollIntoView({behavior:'smooth'})}>Explore the edit <ArrowUpRight size={16}/></button></div><div className="hero-art"><div className="circle-stamp">MAKE<br/>SPACE<br/><small>FOR GOOD</small></div><img src="/products/product-15.webp" alt="Moss lounge chair"/></div></section>
      <section className="ticker"><span>BUILT FOR LIVED-IN SPACES</span><i>✳</i><span>NO FUSS. MORE FEELING.</span><i>✳</i><span>DELIVERED WITH CARE</span></section>
      <section className="catalog"><div className="section-head"><div><p className="eyebrow">THE CURRENT EDIT</p><h2>Find your everyday.</h2></div><div className="searchbox"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search objects"/></div></div><div className="filter-row"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All objects</button>{categories.map(c=><button className={filter===c.id?'selected':''} onClick={()=>setFilter(c.id)} key={c.id}>{c.label}</button>)}</div><div className="product-grid">{shown.map(p=><ProductCard p={p} add={add} key={p.id}/>)}</div></section>
      <section className="manifesto"><div className="manifesto-number">01</div><div><p className="eyebrow">WHY YENFER</p><h2>Less noise.<br/>More living.</h2></div><p>We choose the things that earn their place: durable materials, easy silhouettes, and details that make daily rituals feel lighter. No throwaway trends. Just a considered edit for real homes.</p></section>
    </main><Footer go={go}/>{cartOpen&&<Cart cart={cart} total={total} update={update} close={()=>setCartOpen(false)} checkout={()=>{setCartOpen(false);setView('checkout')}}/>}</>
}
function ProductCard({p,add}){return <article className="card"><div className="card-img"><img src={p.image} alt={p.name}/>{p.tag&&<span>{p.tag}</span>}<button className="quick" onClick={()=>add(p)}>+ Add</button></div><div className="card-meta"><div><h3>{p.name}</h3><p>{categories.find(c=>c.id===p.category)?.label}</p></div><strong>${p.price}</strong></div><button className="buy-link" onClick={()=>add(p,true)}>Buy Now · ${p.price}</button></article>}
function Cart({cart,total,update,close,checkout}){return <div className="overlay"><aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">YOUR BAG</p><h2>Good choices.</h2></div><button className="icon-btn" onClick={close}><X/></button></div>{cart.length===0?<p className="empty">Your bag is waiting for something useful.</p>:<div className="cart-list">{cart.map(p=><div className="cart-item" key={p.id}><img src={p.image}/><div><h3>{p.name}</h3><p>${p.price}</p><div className="qty"><button onClick={()=>update(p.id,-1)}><Minus size={12}/></button><span>{p.qty}</span><button onClick={()=>update(p.id,1)}><Plus size={12}/></button></div></div></div>)}</div>}<div className="drawer-foot"><div><span>Subtotal</span><strong>${total.toFixed(2)}</strong></div><small>Taxes and shipping calculated at checkout.</small><button className="dark-btn full" disabled={!cart.length} onClick={checkout}>Continue to checkout <ArrowUpRight size={16}/></button></div></aside></div>}
function Checkout({cart,total,go}){return <><header className="topbar checkout-top"><a className="wordmark" onClick={()=>go('home')}>YENFER<span>®</span></a><span className="secure">SECURE DEMO CHECKOUT · <button onClick={()=>go('home')}>Return to shop</button></span></header><main className="checkout"><div><p className="eyebrow">CHECKOUT</p><h1>Ready when you are.</h1><p className="muted">This is a front-end demo. No payment is processed.</p><div className="checkout-fields"><label>Email address<input placeholder="you@example.com"/></label><label>Delivery address<input placeholder="Street and unit"/></label><div className="split"><label>City<input placeholder="Singapore"/></label><label>Postal code<input placeholder="000000"/></label></div></div><h3 className="pay-title">Payment method</h3><div className="payments"><button className="pay active"><b>PayPal</b><span>PayPal</span></button><button className="pay"><b>VISA</b><span>Visa</span></button><button className="pay"><b>▣</b><span>Credit / debit card</span></button></div><button className="dark-btn full" onClick={()=>alert('Demo order received — no charge was made.')}>Place demo order <ArrowUpRight size={16}/></button></div><div className="order-summary"><p className="eyebrow">ORDER SUMMARY</p>{cart.map(p=><div className="summary-item" key={p.id}><img src={p.image}/><span>{p.name}<small>Qty {p.qty}</small></span><b>${(p.price*p.qty).toFixed(2)}</b></div>)}<div className="summary-total"><span>Total</span><strong>${total.toFixed(2)}</strong></div></div></main></>}
function InfoPage({page,terms,go}){return <><header className="topbar"><a className="wordmark" onClick={()=>go('home')}>YENFER<span>®</span></a><nav><a onClick={()=>go('home')}>Shop</a><a onClick={()=>go('about')}>Our point of view</a></nav><button className="bag-btn" onClick={()=>go('home')}>Back to shop</button></header><main className="info"><p className="eyebrow">YENFER / INFORMATION</p><h1>{page[0]}</h1><p className="info-intro">{page[1]}</p>{terms?<div className="terms">{terms.map((x,i)=><section key={x}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{x}</h3><p>We act fairly and transparently in relation to {x.toLowerCase()}. Please contact us at {company.email} if you need clarification before using the site or placing an order.</p></div></section>)}</div>:<div className="info-body"><p>{page[1]} We keep our processes clear and our customer support human. Any questions can be directed to our official email address.</p><div className="note"><Check size={18}/><span>Official contact<br/><b>{company.email}</b></span></div></div>}</main><Footer go={go}/></>}
function Admin({go}){return <div className="admin"><div className="admin-card"><p className="eyebrow">YENFER / DEMO ADMIN</p><h1>Welcome back.</h1><p className="muted">Frontend demonstration access only.</p><label>Email<input defaultValue="admin@mfurniture.demo"/></label><label>Password<input type="password" defaultValue="MF2026!demo"/></label><button className="dark-btn full" onClick={()=>go('home')}>Sign in to demo <ArrowUpRight size={16}/></button><p className="admin-hint">Demo login · admin@mfurniture.demo<br/>Password · MF2026!demo</p></div></div>}
function Footer({go}){return <footer><div className="footer-top"><div><a className="wordmark" onClick={()=>go('home')}>YENFER<span>®</span></a><p>Everyday, considered.<br/>Home goods for lived-in spaces.</p></div><div className="footer-links"><div><b>Explore</b><a onClick={()=>go('home')}>Shop all</a><a onClick={()=>go('about')}>About us</a><a onClick={()=>go('tracking')}>Order tracking</a><a onClick={()=>go('admin')}>Admin demo</a></div><div><b>Help & policies</b><a onClick={()=>go('shipping')}>Shipping policy</a><a onClick={()=>go('payments')}>Payment & security</a><a onClick={()=>go('returns')}>Returns & refunds</a><a onClick={()=>go('cancellation')}>Cancellation policy</a></div><div><b>Legal</b><a onClick={()=>go('terms')}>Terms of Service</a><a onClick={()=>go('privacy')}>Privacy policy</a><a onClick={()=>go('dmca')}>DMCA</a></div></div></div><div className="company"><div><b>{company.name}</b><span>{company.address.join(' · ')}</span></div><a href="mailto:MFURNITURESHOP@outlook.com">{company.email}</a></div><div className="copyright"><span>© 2026 M FURNITURE PTE. LTD.</span><span>Made for the everyday.</span></div></footer>}
createRoot(document.getElementById('root')).render(<App/>)
